---
- name: Create systemd service
  template:
    src: crow_service.service.j2
    dest: /etc/systemd/system/crow-http.service
    force: yes
  notify:
    - reload systemd
    - restart crow

- name: Enable and restart service
  systemd:
    name: crow-http
    state: restarted
    enabled: yes