---
- name: Create systemd service for Crow HTTP Server
  template:
    src: crow_service.service.j2
    dest: /etc/systemd/system/crow-http.service
    force: yes
  notify:
    - reload systemd
    - restart crow

- name: Enable and restart Crow HTTP service
  systemd:
    name: crow-http
    state: restarted
    enabled: yes
  when: ansible_service_mgr == "systemd"
  ignore_errors: yes