---
- name: reload systemd
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == "systemd"
  ignore_errors: yes

- name: restart crow
  systemd:
    name: crow-http
    state: restarted
  when: ansible_service_mgr == "systemd"
  ignore_errors: yes
