---
- name: Create systemd service for GraphQL
  template:
    src: graphql_service.service.j2
    dest: /etc/systemd/system/graphql.service
    force: yes
  notify:
    - reload systemd
    - restart graphql

- name: Enable and restart GraphQL service
  systemd:
    name: graphql
    state: restarted
    enabled: yes
  when: ansible_service_mgr == "systemd"
  ignore_errors: yes
